Update MediatR
itmo-is-dev/ASAP pull request #110
Opened 2023-04-19 18:54 UTC by Zisrf

2023-04-20 18:37 UTC, ronimizy requested changes
а можешь ещё по контрактам пробежаться на предмет наличия пустых `record Response()` раз уж на то пошло? я просто когда вижу убираю, но вроде ещё остались места где такое бывает

2023-04-20 18:37 UTC, ronimizy commented on src/core/Application/ITMO.Dev.ASAP.Application.Handlers/Extensions/ServiceCollectionExtensions.cs
> +        collection.AddMediatR(x => x.RegisterServicesFromAssembly(typeof(IAssemblyMarker).Assembly));
```suggestion
        collection.AddMediatR(x => x.RegisterServicesFromAssemblyContaining(typeof(IAssemblyMarker)));
```

2023-04-20 18:37 UTC, ronimizy commented on src/core/DeveloperEnvironment/ITMO.Dev.ASAP.DeveloperEnvironment/ServiceCollectionExtensions.cs
> +        builder.Services.AddMediatR(x => x.RegisterServicesFromAssembly(typeof(IAssemblyMarker).Assembly));
same

2023-04-20 18:37 UTC, ronimizy commented on src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Extensions/ServiceCollectionExtensions.cs
> +        collection.AddMediatR(x => x.RegisterServicesFromAssembly(typeof(IAssemblyMarker).Assembly));
same

2023-04-20 18:37 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Extensions/ServiceCollectionExtensions.cs
> +        collection.AddMediatR(x => x.RegisterServicesFromAssembly(typeof(IAssemblyMarker).Assembly));
same

2023-04-20 18:37 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests/TestBase.cs
> +        collection.AddMediatR(x => x.RegisterServicesFromAssembly(typeof(TestBase).Assembly));
same

2023-04-20 19:48 UTC, Zisrf commented on src/core/Application/ITMO.Dev.ASAP.Application.Handlers/Extensions/ServiceCollectionExtensions.cs
> +        collection.AddMediatR(x => x.RegisterServicesFromAssembly(typeof(IAssemblyMarker).Assembly));
А тебе так просто больше нравится, или есть какая-то разница?

2023-04-23 16:25 UTC, ronimizy approved these changes

2023-04-23 16:25 UTC, ronimizy commented on src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Controllers/ITMO.Dev.ASAP.Github.Presentation.Controllers.csproj
> +
👀

2023-04-23 16:31 UTC, Zisrf commented on src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Controllers/ITMO.Dev.ASAP.Github.Presentation.Controllers.csproj
> +
Ой, что-то нечаянно нажал

2023-04-23 16:42 UTC, merged