fix:points evaluation for transfered student
itmo-is-dev/ASAP pull request #137
Opened 2023-04-27 19:33 UTC by Bl43kburn

Честно говоря, я сам уже сомневаюсь в корректности тестирования этой штуки.

2023-04-27 19:51 UTC, ronimizy requested changes
подразумевалось, что в `StudentAssignment` будет использоваться `Assignment` вместо `GroupAssignment`.
сделай тест на то, что в `StudentPointsDto` все AssignmentId – уникальные.

2023-04-29 08:39 UTC, Bl43kburn commented
Чё-то ребейз за собой все новые коммиты притянуть решил.

2023-05-02 19:10 UTC, ronimizy requested changes

2023-05-02 19:10 UTC, ronimizy commented on src/core/Application/ITMO.Dev.ASAP.Application/Services/SubjectCourseService.cs
> +            .Distinct()
Distinct по кортежу с `IEnumerable` это сильно. ссылки то разные будут.

2023-05-06 15:51 UTC, closed without merging