fix: AssignmentCreatedHandler addition
itmo-is-dev/ASAP pull request #151
Opened 2023-05-11 08:02 UTC by Bl43kburn

2023-05-11 08:03 UTC, Bl43kburn commented
Тесты на инфраструктурные штуки нужно писать?

2023-05-11 14:54 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +
хм, ну вот насчёт этого хз, я бы лучше в таком случае игнорировал ивент, или обновлял сам GithubAssignment, ну офк залоггировав это как варнинг

2023-05-11 14:59 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +
сделай так чтобы обновлялся + логгирование как варнинг

2023-05-14 10:06 UTC, ronimizy requested changes

2023-05-14 10:06 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +        }
это так не работает, напиши тест)

2023-05-20 15:41 UTC, ronimizy requested changes

2023-05-20 15:41 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +    private readonly ILogger<AssignmentCreatedHandler> _logger;
```suggestion
    private readonly IPersistenceContext _context;
    private readonly ILogger<AssignmentCreatedHandler> _logger;
```

2023-05-20 15:41 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +        if (await _context.Assignments.QueryAsync(query, cancellationToken).FirstOrDefaultAsync(cancellationToken) is not null)
1. Сначала проверь, существует ли assignment, сохрани объект в переменную
2. Если придёт `null`, то создавай новый объект, иначе, обнови у существующего объекта данные

2023-05-20 15:41 UTC, ronimizy commented on src/github/ITMO.Dev.ASAP.Github.Common/Exceptions/GithubAssignmentException.cs
> +}
как будто это не нужно

2023-05-20 15:41 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests.Github/Handlers/GithubAssignmentCreatedHandlerTest.cs
> +    public async void Duplicate_Assignment_Should_Log_and_Update()
чёт нейминг вообще не правильный

2023-05-20 15:41 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests.Github/Handlers/GithubAssignmentCreatedHandlerTest.cs
> +    private readonly Mock<ILogger<AssignmentCreatedHandler>> _logger = new Mock<ILogger<AssignmentCreatedHandler>>();
```suggestion
    private readonly Mock<IPersistenceContext> _persistenceContext = new Mock<IPersistenceContext>();
    private readonly Mock<ILogger<AssignmentCreatedHandler>> _logger = new Mock<ILogger<AssignmentCreatedHandler>>();
```

2023-05-20 15:41 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests.Github/Handlers/GithubAssignmentCreatedHandlerTest.cs
> +            Guid.NewGuid(),
заинжекти фейкер (можешь заюзать `DeterministicFaker`) и делай через `faker.Random.Guid(), чтобы айдишники между тест ранами были идентичные

2023-05-20 15:41 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests.Github/Handlers/GithubAssignmentCreatedHandlerTest.cs
> +            .Returns(() => new List<GithubAssignment> { githubAssignment }.ToAsyncEnumerable());
```suggestion
        _persistenceContext
            .Setup(context => context.Assignments.QueryAsync(It.IsAny<GithubAssignmentQuery>(), CancellationToken.None))
            .Returns(() => new List<GithubAssignment> { githubAssignment }.ToAsyncEnumerable());
```

2023-05-20 15:41 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests.Github/Handlers/GithubAssignmentCreatedHandlerTest.cs
> +        // Can't override logger's .log() extenstion method
?

2023-05-20 16:08 UTC, Bl43kburn commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +        if (await _context.Assignments.QueryAsync(query, cancellationToken).FirstOrDefaultAsync(cancellationToken) is not null)
там сеттеров нет, только `init`

2023-05-20 17:39 UTC, ronimizy requested changes

2023-05-20 17:39 UTC, ronimizy commented on src/github/Application/ITMO.Dev.ASAP.Github.Application.Handlers/Assignments/AssignmentCreatedHandler.cs
> +            .FirstOrDefaultAsync(cancellationToken);
```suggestion
        var query = GithubAssignmentQuery.Build(x => x.WithId(assignmentId));

        GithubAssignment? assignment = await _context.Assignments
            .QueryAsync(query, cancellationToken)
            .FirstOrDefaultAsync(cancellationToken);
```

2023-05-20 17:39 UTC, ronimizy commented on tests/ITMO.Dev.ASAP.Tests.Github/Handlers/GithubAssignmentCreatedHandlerTest.cs
> +public class GithubAssignmentCreatedHandlerTest
почитай https://xunit.net/docs/shared-context
таким образом этот тест будет исполняться последовательно с тестами, которые поднимают бд в докере, что не обязательно. лучше просто создай фейкер в конструкторе.

2023-05-20 18:07 UTC, ronimizy approved these changes

2023-05-20 18:07 UTC, merged