Maksise4ka/47 create branch by mentor
itmo-is-dev/ASAP pull request #69
Opened 2023-03-06 07:49 UTC by Maksise4ka

2023-03-06 11:47 UTC, ronimizy requested changes
ну и эксепшены нормальные бы сделать, да)

2023-03-06 11:56 UTC, Maksise4ka commented on Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/UserRoleType.cs
> +}
Типа кучу булевых свойств сделать, типа проверки, имеет ли ICurrentUser ко всей информации?

2023-03-06 13:23 UTC, Maksise4ka commented on Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/UserRoleType.cs
> +}
А можно где-нибудь сделать namespace для application-исключений, если да, то где? А то тут хочется кастомное исключение сделать

2023-03-06 13:25 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/UserRoleType.cs
> +}
> А можно где-нибудь сделать namespace для application-исключений, если да, то где? А то тут хочется кастомное исключение сделать

Можешь сделать проект ITMO.Dev.ASAP.Application.Common и там эксепшены приложения. в целом потом можно будет их переместить куда-нибудь, если будет не логично казаться, главное чтобы они были

2023-03-06 16:57 UTC, ronimizy requested changes

2023-03-06 16:58 UTC, ronimizy commented
В `GetSubjectCoursesBySubjectIdHandler` тоже бы проверку добавить

2023-03-06 17:05 UTC, Maksise4ka commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Subjects/GetSubjectsHandler.cs
> +            throw UserHasNotAccessException.EmptyAvailableList(_currentUser.Id);
"Получение курсов по предмету, должно выдавать ошибку, если пользователь не является ментором ни на одном из курсов." Это из таски

2023-03-06 18:22 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Subjects/GetSubjectsHandler.cs
> +            throw UserHasNotAccessException.EmptyAvailableList(_currentUser.Id);
но это получение предметов, а не курсов по предмету

2023-03-06 18:38 UTC, Maksise4ka commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesHandler.cs
>              .ToListAsync(cancellationToken);
так я же это в FilterAvailableSubjectCourses внутри ICurrentUser делаю. Мне нужно еще извне проверять? Тогда смысла в этом методе нет

2023-03-14 20:48 UTC, ronimizy requested changes

2023-03-14 20:48 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
```suggestion
        Subject subject = await _context.Subjects
            .Include(x => x.Courses)
            .GetByIdAsync(request.SubjectId, cancellationToken);

```

2023-03-14 20:48 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
> +            .ToList();
```suggestion
        var availableSubjectCourses = subject.Courses
            .Where(_currentUser.HasAccessToSubjectCourse)
            .ToList();
```

2023-03-14 20:48 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Subjects/GetSubjectByIdHandler.cs
>              .GetByIdAsync(request.Id, cancellationToken);
```suggestion
        Subject subject = await _context.Subjects
            .Include(x => x.Courses)
            .GetByIdAsync(request.Id, cancellationToken);
```

2023-03-14 20:48 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Subjects/GetSubjectsHandler.cs
> +            .ToListAsync(cancellationToken);
напиши тест на этот хендлер

2023-03-25 07:15 UTC, ronimizy requested changes

2023-03-25 07:15 UTC, ronimizy commented on Source/Tests/ITMO.Dev.ASAP.Tests.Handlers/Study/Subjects/GetSubjectTest.cs
> +            () => handler.Handle(query, CancellationToken.None));
```suggestion
        var handler = new GetSubjectsHandler(Context, anonymousUser);
        var query = new GetSubjects.Query();

        await Assert.ThrowsAsync<UserHasNotAccessException>(
            () => handler.Handle(query, CancellationToken.None));
```

2023-03-25 07:15 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
> +            throw UserHasNotAccessException.EmptyAvailableList(_currentUser.Id);
вот это место меня смущает. получается что мы делаем две одинаковых проверки. логику дублируем по факту.

2023-03-25 07:17 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
> +            throw UserHasNotAccessException.EmptyAvailableList(_currentUser.Id);
например, если админ попытается открыть страничку предмета, на которой вызывается получение курсов по нему, если ни одного курса задано не было, он получит ошибку, что у него нет доступа.

2023-03-25 07:18 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
> +            throw UserHasNotAccessException.EmptyAvailableList(_currentUser.Id);
плюс, если ты не будешь делать эту проверку, то можешь сразу после этого `Where` `Select`'ить в дто и не выделять лишний массив под сущности.

2023-03-25 07:54 UTC, Maksise4ka commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
> +            throw UserHasNotAccessException.EmptyAvailableList(_currentUser.Id);
По идее последняя проверка нужна только для ментора, и в методе HasAccessToSubject у Mentor я как раз проверяю, что он имеет доступ к предмету если имеет доступ хотя бы к одному предмету. Так что эту проверку я уберу

2023-03-25 07:58 UTC, ronimizy approved these changes

2023-03-25 08:21 UTC, merged