DianaNeumann/58 Queue SignalR Backend
itmo-is-dev/ASAP pull request #71
Opened 2023-03-10 03:42 UTC by DianaNeumann

2023-03-10 19:04 UTC, ronimizy requested changes
чуток не совсем то, что я ожидал.
выходит, что генерация очереди – копипаста старого кода. думаю стоит вынести эту логику отдельный сервис и вызывать в в твоём хендлере, и в том, что дёргает воркер (либо просто перенести обработку этого реквеста в тот хендлер).
вообще хотелось бы, чтобы очередь не пересчитывала без надобности, почитай про `IMemoryCache`, добавь его сюда.

2023-03-13 22:59 UTC, DianaNeumann commented
тогда создавал PR в 6 утра или типа того и не заметил, что master стоял))

2023-03-14 20:43 UTC, ronimizy requested changes
не вижу интеграции с существующим обновлением очередей 🤔

2023-03-14 20:43 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Contracts/Study/Queues/Queries/GetSubmmissionsQueueBySubjectCourseGroupIds.cs
> +internal static class GetSubmmissionsQueueBySubjectCourseGroupIds
пока у нас нет кастомных очередей, так что можно обойтись таким неймингом 

```suggestion
internal static class GetSubmmissionsQueue
```

2023-03-14 20:43 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/GetSubmmissionsQueueBySubjectCourseGroupIdsHandler.cs
> +            .SetPriority(CacheItemPriority.Normal);
а зачем? очередь по факту сама не устаревает. если есть какое-то событие, которое приводит к её устареванию, то оно тригерит перегенерацию очереди, что потом должно приводить к обновлению кеша

2023-03-14 20:43 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Abstractions/IQueueHub.cs
> +public interface IQueueHub
```suggestion
public interface IQueueHubClient
```

2023-03-14 20:43 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Abstractions/IQueueHub.cs
> +    Task SendUpdateQueueMessage(SubmissionsQueueDto submissionsQueue, CancellationToken cancellationToken);
ух, у меня есть плохой опыт с CancellationToken'ами и SignalR, сейчас пусть будет, но если в будущем появятся проблемы с model binding'ом, то имей в виду, что проблема может быть в этом

2023-03-14 20:43 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Contracts/Study/Queues/Notifications/ClearSubmissionsQueueCache.cs
> +}
для этого не нужно делать отдельную нотификашку, нужно хендлить `SubmissionsQueueUpdated` для этого

2023-03-24 21:19 UTC, DianaNeumann commented
там с импортом GetSubmmissionsQueue траблы какие-то, оставил public пока, райдер не видит тип вообще (даже с internalVisible), мб райдер лагает. Исправлю

2023-03-25 07:20 UTC, ronimizy commented
> там с импортом GetSubmmissionsQueue траблы какие-то, оставил public пока, райдер не видит тип вообще (даже с internalVisible), мб райдер лагает. Исправлю

пробовал перебилдить проект?

2023-03-25 07:25 UTC, DianaNeumann commented
> > там с импортом GetSubmmissionsQueue траблы какие-то, оставил public пока, райдер не видит тип вообще (даже с internalVisible), мб райдер лагает. Исправлю
> 
> пробовал перебилдить проект?

ага

2023-03-25 07:41 UTC, ronimizy requested changes
давай крч объясню чуть-подробнее, почему твой способ (сначала чистить кеш, а потом обновлять сервисом) мне не особо нравится.

вся суть с тем, чтобы публиковать нотификейшн о том, что очередь обновилась, заключается в том, что мы убираем high coupling между генерацией очереди, обновлением кеша, и публикацией этих данных куда-то (Гугл, сигнал). \
если ты сначала удаляешь кеш, то ты завязываешься на реализацию внутри хендлера команды, что он работает с кешом.

тебе не надо работать с реквестом в воркере, просто публикуй нотификашку о том, что надо обновить таблицу, в хендлере для неё, используй сервис, чтобы её пересчитать, и кеш обновляй, как раз по нотификашке о том, что очередь уже пересчиталась

2023-03-25 07:41 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Google/Workers/GoogleTableUpdateWorker.cs
>      }
?

2023-03-25 07:41 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/GetSubmmissionsQueueHandler.cs
> +        }
```suggestion
        string cacheKey = string.Concat(request.SubjectCourseId, request.GroupId);

        if (_cache.TryGetValue(cacheKey, out SubmissionsQueueDto submissionsQueue))
        {
            return new Response(submissionsQueue);
        }
```

2023-03-25 07:41 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/GetSubmmissionsQueueHandler.cs
> +        _cache.Set(cacheKey, submissionsQueue, cacheEntryOptions);
```suggestion
        _cache.Set(cacheKey, submissionsQueue);
```

2023-03-25 07:41 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Handlers/QueueUpdateNotificationHandler.cs
> +        await _hubContext.Clients.All.SendUpdateQueueMessage(submissionsQueue, cancellationToken);
ну, всем рассылать не стоит. думаю в хабе надо сделать метод, который подписывается/отписывается на обновления очереди (через группы), чтобы клиент получал информацию только о тех очередях, что ему нужно

2023-03-25 07:41 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Handlers/QueueUpdateNotificationHandler.cs
> +        await _hubContext.Clients.All.SendUpdateQueueMessage(submissionsQueue, cancellationToken);
когда будешь это ^ имплементить, поймёшь, что тебе в нотификашке не хватает данных, надо ещё знать айдишник SubjectCourse и StudentGroup чтобы в нужную группу отправлять

2023-03-25 07:41 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Google/Workers/GoogleTableUpdateWorker.cs
> +            await _mediator.Send(notification, cancellationToken);
упадёт, с `Notification` нельзя юзать `Send`, нужен `Publish`

2023-03-25 07:41 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Google/Workers/GoogleTableUpdateWorker.cs
> +            Response response = await _mediator.Send(getSubmissionsQuery, cancellationToken);
не надо использовать реквесты изнутри приложения, нотификашки - ок, но реквесты предназначены для коммуникации с приложением извне (с презентейшена)

2023-03-28 09:09 UTC, DianaNeumann commented
Осталось подумать где будет происходить добавление клиента в группу

2023-03-29 18:34 UTC, ronimizy requested changes

2023-03-29 18:34 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Handlers/QueueUpdateNotificationHandler.cs
> +    }
1. давным давно мы договорились, что реквесты из хендлеров мы не кидаем. в конце концов это приведёт к с сложному графу зависимостей между ними, и, из-за их природы, циклические зависимости будут неявными, и DI их допустит, что превратит их структуру в спагетти (буквально)
2. мне всё ещё не нравится флоу логики. оповещение об обновлении очереди, должно происходить как РЕАКЦИЯ на то, что она была пересчитана. на данный момент, ты неявно запускаешь её пересчёт из презентейшена, не смотря на то, что это часть логики приложения. почему неявно? потому что, если бы ты разрабатывал только презентейшн, т.е. все остальные слои были бы для тебя чёрным ящиком, ты не мог бы никак гарантировать то, что обрабатывая такое обновление, что-то и правда обновилось. на самом деле ты и сейчас этого гарантировать не можешь, так как нельзя, глядя на код, с уверенностью сказать, в каком порядке будут вызываться хендлеры этой нотификашки. может произойти так, что сначала будет обновление хаба, а потом почистится кеш.

2023-04-11 18:40 UTC, ronimizy requested changes

2023-04-11 18:40 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Google/SubjectCourseGroupQueueUpdateHandler.cs
> +        IPublisher publisher = serviceScope.ServiceProvider.GetRequiredService<IPublisher>();
не понимаю зачем вот так везде делаешь, хендлер уже создаётся в скоре

2023-04-11 18:40 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Google/SubjectCourseGroupQueueUpdateHandler.cs
> +        await publisher.Publish(updateCacheNotification, cancellationToken);
```suggestion
        var updatedNotification = new QueueUpdated.Notification(
            notification.SubjectCourseId,
            notification.GroupId,
            submissionsQueue);

        await publisher.Publish(updatedNotification, cancellationToken);
```

2023-04-11 18:40 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/UpdateQueueCacheNotificationHandler.cs
> +        publisher.Publish(queueUpdatedNotification, cancellationToken);
вот это ивент луп
(тут зациклится выполнение)

2023-04-11 18:40 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Handlers/QueueUpdateNotificationHandler.cs
> +            .SendUpdateQueueMessage(notification.SubmissionsQueue, cancellationToken);
```suggestion
       var group =_hubContext.Clients.Group(notificationGroup);
        await group.SendUpdateQueueMessage(notification.SubmissionsQueue, cancellationToken);
```

2023-04-11 18:40 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Hubs/QueueHub.cs
> +    public Task AddGroup(Guid courseId, Guid groupId)
```suggestion
    public Task QueueUpdateSubscribe(Guid courseId, Guid groupId)
```

2023-04-11 18:40 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Hubs/QueueHub.cs
> +    public Task RemoveGroup(Guid courseId, Guid groupId)
```suggestion
    public Task QueueUpdateUnubscribe(Guid courseId, Guid groupId)
```

2023-04-12 07:14 UTC, ronimizy commented on Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Hubs/QueueHub.cs
> +    public Task QueueUpdateUnubscribe(Guid courseId, Guid groupId)
```suggestion
    public Task QueueUpdateUnsubscribe(Guid courseId, Guid groupId)
```

2023-04-12 07:15 UTC, ronimizy approved these changes
порешай конфликты и можешь мержить

2023-04-14 18:14 UTC, merged