Zisrf/74 create user account testing
itmo-is-dev/ASAP pull request #85
Opened 2023-04-01 21:04 UTC by Zisrf

2023-04-02 08:56 UTC, ronimizy requested changes
По сути сделано правильно. Но, есть кое что, что мне давно не нравятся насчёт того, как сделана работа с identity в проекте.

зависимость от identity framework тянется везде где нужно знать роли
по факту нарушается инверсия зависимостей, хотелось бы, чтобы это всё было вынесено на уровень абстракций, чтобы не: `.Controllers -> .Identity -> IdentityFramework`, а `.Controllers -> .Abstractions <- .Identity -> IdentityFramework`

думаю, что нам не нужно оперировать identity сущностями напрямую из бизнес логики, а лучше из identity service'a возвращать dto, включающие только нужную информацию. таким образом, можно будет положить его интерфейс в `.Application.Abstractions`, где ему и место

2023-04-02 08:56 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/Services/IIdentitySetvice.cs
> +public interface IIdentitySetvice
опечатка в названии, ну и как-то вот это `II` не смотрится, я бы всё-таки вернулся к `IAuthorizationService`

2023-04-02 13:27 UTC, ronimizy requested changes

2023-04-02 13:27 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Users/GitUserIdentityInfosHandler.cs
> +    private readonly UserManager<AsapIdentityUserDto> _userManager;
👀

2023-04-02 13:27 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.DataAccess/ValueConverters/SpbDateTimeValueConverter.cs
> +    { }
👀

2023-04-02 13:27 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/Models/AsapIdentityRoleNames.cs
> +}
это скорее в `.Application.Common` стоит положить, так как используется и приложением и презентейшеном

2023-04-02 13:27 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/ITMO.Dev.ASAP.Identity.Abstractions.csproj
> +</Project>
не думаю, что есть особый смысл под это выделять отдельный проект, тем более в инфраструктуре

положи интерфейс в `.Application.Abstractions`, а с дто, просто расширь существующий `IdentityUserDto`

2023-04-02 13:49 UTC, Zisrf commented on Source/Application/ITMO.Dev.ASAP.Application.Handlers/Users/GitUserIdentityInfosHandler.cs
> +    private readonly UserManager<AsapIdentityUserDto> _userManager;
Рефакторинг вышел из под контроля

2023-04-02 14:03 UTC, Zisrf commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/ITMO.Dev.ASAP.Identity.Abstractions.csproj
> +</Project>
А в чём отличие от DataAccess.Abstractions ?

2023-04-02 14:05 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/ITMO.Dev.ASAP.Identity.Abstractions.csproj
> +</Project>
в целом никакого, то, что абстракции для дб лежат в инфраструктуре мне тож не очень нравится, но это уже другая история :)

2023-04-02 18:04 UTC, Zisrf commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/ITMO.Dev.ASAP.Identity.Abstractions.csproj
> +</Project>
Тоже лучше было бы не завязываться на DbSet'ах, а использовать какие-то абстрактные репозитории?

2023-04-02 19:29 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity.Abstractions/ITMO.Dev.ASAP.Identity.Abstractions.csproj
> +</Project>
там чуть посложнее, либо у тебя еф просачивается достаточно обширно, либо ты сильно его оборачиваешь. мне кажется, что в этом нет особого смысла, поэтому зависимости еф протекают больше чем должно быть в идеале. пока что, я бы ограничился тем, что абстракции для бд стоит перенести к остальным вторичным портам, в приложение. но это в рамки данного пр не входит.

2023-04-03 13:24 UTC, ronimizy requested changes

2023-04-03 13:24 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/IAuthorizationService.cs
> +    IReadOnlyCollection<IdentityUserDto> Users { get; }
👀

2023-04-03 13:24 UTC, ronimizy commented on Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/IAuthorizationService.cs
> +    IReadOnlyCollection<IdentityUserDto> Users { get; }
грузить всех юзеров в память, ещё и синхронно...

2023-04-03 13:24 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Services/AuthorizationService.cs
> +    }
такая реализация не работает, выдаёт ошибку, что у юзера уже есть пароль

https://github.com/itmo-is-dev/ASAP/blob/72ac0b8c447e08c5a828d146a3d3bd96049a0169/Source/Application/ITMO.Dev.ASAP.Application.Handlers/Identity/UpdatePasswordHandler.cs#L26-L38

2023-04-03 13:24 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Services/AuthorizationService.cs
> +            throw new UpdateUsernameFailedException(string.Join(' ', result.Errors.Select(r => r.Description)));
вот это бы вынести в экстеншен, чтобы не копипастить одинаковый код

2023-04-03 13:24 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Services/AuthorizationService.cs
> +        return passwordCorrect;
```suggestion
        AsapIdentityUser user = await _userManager.GetByIdAsync(userId, cancellationToken);

        return await _userManager.CheckPasswordAsync(user, password);
```

2023-04-03 13:52 UTC, Zisrf commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Services/AuthorizationService.cs
> +    }
А я её и не писал, просто перенёс из соответствующего хендлера :)

2023-04-03 13:53 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Services/AuthorizationService.cs
> +    }
ну я прост у себя в таске на это наткнулся)

2023-04-04 14:28 UTC, ronimizy requested changes

2023-04-04 14:28 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Exceptions/IdentityException.cs
> +}
удачи потом это отлавливать)
я вообще имел в виду экстеншн метод над IdentityResult типа `EnsureSucceeded`

2023-04-04 14:30 UTC, ronimizy commented on Source/Infrastructure/ITMO.Dev.ASAP.Identity/Exceptions/IdentityException.cs
> +}
который при неудаче будет кидать эксепшен из `.Application.Common`

2023-04-05 15:51 UTC, merged